/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import View.LoginPage;
import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import Controller.*;
import Model.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class AdminPage extends javax.swing.JFrame {
    LoginDTO logindto = new LoginDTO();
    ArticleDTO articledto = new ArticleDTO();
    DefaultTableModel tblArticle;
    DefaultTableModel tblUser;
    int page = 1;

    /**
     * Creates new form UserProfilePage
     */
    public AdminPage() {
        initComponents();
        setLocationRelativeTo(null);
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 20, 20));
        initObject();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new com.k33ptoo.components.KGradientPanel();
        LeftMenuPanel = new javax.swing.JPanel();
        OverviewPanel = new Test.JPanelRounded();
        OverviewTitleLabel = new javax.swing.JLabel();
        RightColorPanel1 = new Test.JPanelRounded();
        PostsPanel = new Test.JPanelRounded();
        PostsTitleLabel = new javax.swing.JLabel();
        RightColorPanel3 = new Test.JPanelRounded();
        AccountsPanel = new Test.JPanelRounded();
        AccountsTitleLabel = new javax.swing.JLabel();
        RightColorPanel2 = new Test.JPanelRounded();
        TopMenuPanel1 = new javax.swing.JPanel();
        HomeLinkPanel = new javax.swing.JPanel();
        HomeLinkLabel = new javax.swing.JLabel();
        SettingLinkPanel = new javax.swing.JPanel();
        SettingLinkLabel = new javax.swing.JLabel();
        CateLinkPanel = new javax.swing.JPanel();
        CateLinkLabel = new javax.swing.JLabel();
        ExitBtn = new javax.swing.JLabel();
        TopMenuPanel2 = new javax.swing.JPanel();
        SearchBorderPanel = new javax.swing.JPanel();
        InputSearch = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CardLayoutSpace = new javax.swing.JPanel();
        OverviewLayoutPanel = new javax.swing.JPanel();
        TotalPostsPanel = new Test.JPanelRounded();
        TotalPostIcon = new javax.swing.JLabel();
        TotalPostTitleLabel = new javax.swing.JLabel();
        PostsAmount = new javax.swing.JLabel();
        SmallOverviewPanel = new Test.JPanelRounded();
        TopPostMonthTitle = new javax.swing.JLabel();
        TipsLabel = new javax.swing.JLabel();
        Top1PostImage = new javax.swing.JLabel();
        Top2PostImage = new javax.swing.JLabel();
        Top1PostTitle = new javax.swing.JLabel();
        Top2PostTitle = new javax.swing.JLabel();
        AuthorUsername1 = new javax.swing.JLabel();
        AuthorUsername2 = new javax.swing.JLabel();
        TotalUsersPanel = new Test.JPanelRounded();
        TotalUsersIcon = new javax.swing.JLabel();
        UsersAmount = new javax.swing.JLabel();
        TotalUsersTitleLabel = new javax.swing.JLabel();
        RatingPanel = new Test.JPanelRounded();
        RatingAmount = new javax.swing.JLabel();
        RatingTitleLabel = new javax.swing.JLabel();
        RatingIcon = new javax.swing.JLabel();
        DetailPostLayout = new javax.swing.JPanel();
        SmallDPPanel = new Test.JPanelRounded();
        Submit = new com.k33ptoo.components.KButton();
        PostImage = new javax.swing.JLabel();
        PostContentScrollPane = new javax.swing.JScrollPane();
        PostContent = new javax.swing.JTextArea();
        PostTitleScrollPane = new javax.swing.JScrollPane();
        PostTitle = new javax.swing.JTextArea();
        PostsLayoutPanel = new javax.swing.JPanel();
        SmallPostPanel = new Test.JPanelRounded();
        AcceptBtn = new com.k33ptoo.components.KButton();
        PostTableScrollPane = new javax.swing.JScrollPane();
        PostTable = new javax.swing.JTable();
        DeleteButton = new com.k33ptoo.components.KButton();
        AccountsLayoutPanel = new javax.swing.JPanel();
        SmallAccountPanel = new Test.JPanelRounded();
        AccountTableSrcollPane = new javax.swing.JScrollPane();
        AccountTable = new javax.swing.JTable();
        kButton1 = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        setSize(new java.awt.Dimension(0, 0));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainPanel.setBackground(new java.awt.Color(35, 35, 35));
        MainPanel.setkBorderRadius(30);
        MainPanel.setkEndColor(new java.awt.Color(35, 35, 35));
        MainPanel.setkStartColor(new java.awt.Color(35, 35, 35));
        MainPanel.setPreferredSize(new java.awt.Dimension(1300, 731));
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LeftMenuPanel.setBackground(new java.awt.Color(35, 35, 35));
        LeftMenuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OverviewPanel.setBackground(new java.awt.Color(35, 35, 35));
        OverviewPanel.setRoundBottomLeft(30);
        OverviewPanel.setRoundTopLeft(30);
        OverviewPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OverviewPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OverviewPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OverviewPanelMouseExited(evt);
            }
        });
        OverviewPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OverviewTitleLabel.setBackground(new java.awt.Color(255, 255, 255));
        OverviewTitleLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        OverviewTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        OverviewTitleLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_museum_30px.png"))); // NOI18N
        OverviewTitleLabel.setText("  Overview");
        OverviewTitleLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OverviewTitleLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OverviewTitleLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OverviewTitleLabelMouseExited(evt);
            }
        });
        OverviewPanel.add(OverviewTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 130, 30));

        RightColorPanel1.setBackground(new java.awt.Color(204, 255, 204));
        RightColorPanel1.setRoundBottomLeft(25);
        RightColorPanel1.setRoundTopLeft(25);

        javax.swing.GroupLayout RightColorPanel1Layout = new javax.swing.GroupLayout(RightColorPanel1);
        RightColorPanel1.setLayout(RightColorPanel1Layout);
        RightColorPanel1Layout.setHorizontalGroup(
            RightColorPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        RightColorPanel1Layout.setVerticalGroup(
            RightColorPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        OverviewPanel.add(RightColorPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 90));

        LeftMenuPanel.add(OverviewPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 260, 90));

        PostsPanel.setBackground(new java.awt.Color(35, 35, 35));
        PostsPanel.setForeground(new java.awt.Color(51, 51, 51));
        PostsPanel.setRoundBottomLeft(30);
        PostsPanel.setRoundTopLeft(30);
        PostsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PostsPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PostsPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PostsPanelMouseExited(evt);
            }
        });
        PostsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PostsTitleLabel.setBackground(new java.awt.Color(255, 255, 255));
        PostsTitleLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        PostsTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        PostsTitleLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_page_30px_1.png"))); // NOI18N
        PostsTitleLabel.setText("  Posts");
        PostsTitleLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PostsTitleLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PostsTitleLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PostsTitleLabelMouseExited(evt);
            }
        });
        PostsPanel.add(PostsTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 140, 30));

        RightColorPanel3.setBackground(new java.awt.Color(204, 255, 204));
        RightColorPanel3.setRoundBottomLeft(25);
        RightColorPanel3.setRoundTopLeft(25);

        javax.swing.GroupLayout RightColorPanel3Layout = new javax.swing.GroupLayout(RightColorPanel3);
        RightColorPanel3.setLayout(RightColorPanel3Layout);
        RightColorPanel3Layout.setHorizontalGroup(
            RightColorPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        RightColorPanel3Layout.setVerticalGroup(
            RightColorPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        PostsPanel.add(RightColorPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        LeftMenuPanel.add(PostsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 260, 90));

        AccountsPanel.setBackground(new java.awt.Color(35, 35, 35));
        AccountsPanel.setRoundBottomLeft(30);
        AccountsPanel.setRoundTopLeft(30);
        AccountsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccountsPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AccountsPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AccountsPanelMouseExited(evt);
            }
        });
        AccountsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AccountsTitleLabel.setBackground(new java.awt.Color(255, 255, 255));
        AccountsTitleLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        AccountsTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        AccountsTitleLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_account_30px.png"))); // NOI18N
        AccountsTitleLabel.setText("  Accounts");
        AccountsTitleLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccountsTitleLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AccountsTitleLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AccountsTitleLabelMouseExited(evt);
            }
        });
        AccountsPanel.add(AccountsTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 130, 30));

        RightColorPanel2.setBackground(new java.awt.Color(204, 255, 204));
        RightColorPanel2.setRoundBottomLeft(25);
        RightColorPanel2.setRoundTopLeft(25);

        javax.swing.GroupLayout RightColorPanel2Layout = new javax.swing.GroupLayout(RightColorPanel2);
        RightColorPanel2.setLayout(RightColorPanel2Layout);
        RightColorPanel2Layout.setHorizontalGroup(
            RightColorPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        RightColorPanel2Layout.setVerticalGroup(
            RightColorPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        AccountsPanel.add(RightColorPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 90));

        LeftMenuPanel.add(AccountsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 260, 90));

        MainPanel.add(LeftMenuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 280, 670));

        TopMenuPanel1.setBackground(new java.awt.Color(10, 10, 10));
        TopMenuPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HomeLinkPanel.setBackground(new java.awt.Color(0, 0, 0));
        HomeLinkPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeLinkPanelMouseClicked(evt);
            }
        });

        HomeLinkLabel.setBackground(new java.awt.Color(255, 255, 255));
        HomeLinkLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        HomeLinkLabel.setForeground(new java.awt.Color(255, 255, 255));
        HomeLinkLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_home_20px.png"))); // NOI18N
        HomeLinkLabel.setText("Home");
        HomeLinkLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeLinkLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeLinkLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeLinkLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout HomeLinkPanelLayout = new javax.swing.GroupLayout(HomeLinkPanel);
        HomeLinkPanel.setLayout(HomeLinkPanelLayout);
        HomeLinkPanelLayout.setHorizontalGroup(
            HomeLinkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
            .addGroup(HomeLinkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HomeLinkPanelLayout.createSequentialGroup()
                    .addGap(0, 13, Short.MAX_VALUE)
                    .addComponent(HomeLinkLabel)
                    .addGap(0, 14, Short.MAX_VALUE)))
        );
        HomeLinkPanelLayout.setVerticalGroup(
            HomeLinkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(HomeLinkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HomeLinkPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(HomeLinkLabel)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        TopMenuPanel1.add(HomeLinkPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 90, 30));

        SettingLinkPanel.setBackground(new java.awt.Color(0, 0, 0));

        SettingLinkLabel.setBackground(new java.awt.Color(255, 255, 255));
        SettingLinkLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SettingLinkLabel.setForeground(new java.awt.Color(255, 255, 255));
        SettingLinkLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_settings_25px_1.png"))); // NOI18N
        SettingLinkLabel.setText("Setting");
        SettingLinkLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SettingLinkLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SettingLinkLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SettingLinkLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout SettingLinkPanelLayout = new javax.swing.GroupLayout(SettingLinkPanel);
        SettingLinkPanel.setLayout(SettingLinkPanelLayout);
        SettingLinkPanelLayout.setHorizontalGroup(
            SettingLinkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
            .addGroup(SettingLinkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SettingLinkPanelLayout.createSequentialGroup()
                    .addGap(0, 8, Short.MAX_VALUE)
                    .addComponent(SettingLinkLabel)
                    .addGap(0, 8, Short.MAX_VALUE)))
        );
        SettingLinkPanelLayout.setVerticalGroup(
            SettingLinkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(SettingLinkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SettingLinkPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(SettingLinkLabel)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        TopMenuPanel1.add(SettingLinkPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 90, -1));

        CateLinkPanel.setBackground(new java.awt.Color(0, 0, 0));

        CateLinkLabel.setBackground(new java.awt.Color(255, 255, 255));
        CateLinkLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CateLinkLabel.setForeground(new java.awt.Color(255, 255, 255));
        CateLinkLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_sorting_25px_1.png"))); // NOI18N
        CateLinkLabel.setText("Categories");
        CateLinkLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CateLinkLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CateLinkLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CateLinkLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout CateLinkPanelLayout = new javax.swing.GroupLayout(CateLinkPanel);
        CateLinkPanel.setLayout(CateLinkPanelLayout);
        CateLinkPanelLayout.setHorizontalGroup(
            CateLinkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
            .addGroup(CateLinkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CateLinkPanelLayout.createSequentialGroup()
                    .addGap(0, 7, Short.MAX_VALUE)
                    .addComponent(CateLinkLabel)
                    .addGap(0, 7, Short.MAX_VALUE)))
        );
        CateLinkPanelLayout.setVerticalGroup(
            CateLinkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(CateLinkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CateLinkPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(CateLinkLabel)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        TopMenuPanel1.add(CateLinkPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 110, -1));

        ExitBtn.setForeground(new java.awt.Color(255, 255, 255));
        ExitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_Close_20px_1.png"))); // NOI18N
        ExitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitBtnMouseClicked(evt);
            }
        });
        TopMenuPanel1.add(ExitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 20, -1, 30));

        MainPanel.add(TopMenuPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 60));

        TopMenuPanel2.setBackground(new java.awt.Color(255, 255, 255));

        SearchBorderPanel.setBackground(new java.awt.Color(255, 255, 255));
        SearchBorderPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        SearchBorderPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InputSearch.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        InputSearch.setText("Search content..");
        InputSearch.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        InputSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InputSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                InputSearchFocusLost(evt);
            }
        });
        InputSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InputSearchMouseClicked(evt);
            }
        });
        InputSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputSearchActionPerformed(evt);
            }
        });
        SearchBorderPanel.add(InputSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 40));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_search_30px.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        SearchBorderPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 30, 40));

        javax.swing.GroupLayout TopMenuPanel2Layout = new javax.swing.GroupLayout(TopMenuPanel2);
        TopMenuPanel2.setLayout(TopMenuPanel2Layout);
        TopMenuPanel2Layout.setHorizontalGroup(
            TopMenuPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopMenuPanel2Layout.createSequentialGroup()
                .addContainerGap(642, Short.MAX_VALUE)
                .addComponent(SearchBorderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        TopMenuPanel2Layout.setVerticalGroup(
            TopMenuPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopMenuPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(SearchBorderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        MainPanel.add(TopMenuPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 1020, 70));

        CardLayoutSpace.setBackground(new java.awt.Color(238, 238, 238));
        CardLayoutSpace.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CardLayoutSpaceFocusGained(evt);
            }
        });
        CardLayoutSpace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CardLayoutSpaceMouseClicked(evt);
            }
        });
        CardLayoutSpace.setLayout(new java.awt.CardLayout());

        OverviewLayoutPanel.setBackground(new java.awt.Color(238, 238, 238));
        OverviewLayoutPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TotalPostsPanel.setBackground(new java.awt.Color(255, 255, 255));
        TotalPostsPanel.setRoundBottomLeft(15);
        TotalPostsPanel.setRoundBottomRight(15);
        TotalPostsPanel.setRoundTopLeft(15);
        TotalPostsPanel.setRoundTopRight(15);
        TotalPostsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TotalPostIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_playlist_50px.png"))); // NOI18N
        TotalPostsPanel.add(TotalPostIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 40));

        TotalPostTitleLabel.setForeground(new java.awt.Color(102, 102, 102));
        TotalPostTitleLabel.setText("Total Posts");
        TotalPostsPanel.add(TotalPostTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        PostsAmount.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        PostsAmount.setForeground(new java.awt.Color(51, 51, 51));
        PostsAmount.setText("1000");
        TotalPostsPanel.add(PostsAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 90, 20));

        OverviewLayoutPanel.add(TotalPostsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 230, 80));

        SmallOverviewPanel.setBackground(new java.awt.Color(255, 255, 255));
        SmallOverviewPanel.setRoundBottomLeft(15);
        SmallOverviewPanel.setRoundBottomRight(15);
        SmallOverviewPanel.setRoundTopLeft(15);
        SmallOverviewPanel.setRoundTopRight(15);
        SmallOverviewPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TopPostMonthTitle.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        TopPostMonthTitle.setForeground(new java.awt.Color(51, 51, 51));
        TopPostMonthTitle.setText("Top post of this month ");
        SmallOverviewPanel.add(TopPostMonthTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        TipsLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TipsLabel.setForeground(new java.awt.Color(102, 102, 102));
        TipsLabel.setText("User having a post on top record board will be sent a gift");
        SmallOverviewPanel.add(TipsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        Top1PostImage.setText("Image1");
        SmallOverviewPanel.add(Top1PostImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 380, 190));

        Top2PostImage.setText("Image2");
        SmallOverviewPanel.add(Top2PostImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 380, 190));

        Top1PostTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Top1PostTitle.setForeground(new java.awt.Color(51, 51, 51));
        Top1PostTitle.setText("TitleTop1Post");
        SmallOverviewPanel.add(Top1PostTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 380, -1));

        Top2PostTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Top2PostTitle.setForeground(new java.awt.Color(51, 51, 51));
        Top2PostTitle.setText("TitleTop2Post");
        SmallOverviewPanel.add(Top2PostTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 380, -1));

        AuthorUsername1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AuthorUsername1.setForeground(new java.awt.Color(102, 102, 102));
        AuthorUsername1.setText("Author1");
        SmallOverviewPanel.add(AuthorUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, -1));

        AuthorUsername2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AuthorUsername2.setForeground(new java.awt.Color(102, 102, 102));
        AuthorUsername2.setText("Author2");
        SmallOverviewPanel.add(AuthorUsername2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 330, -1, -1));

        OverviewLayoutPanel.add(SmallOverviewPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 930, 450));

        TotalUsersPanel.setBackground(new java.awt.Color(255, 255, 255));
        TotalUsersPanel.setRoundBottomLeft(15);
        TotalUsersPanel.setRoundBottomRight(15);
        TotalUsersPanel.setRoundTopLeft(15);
        TotalUsersPanel.setRoundTopRight(15);
        TotalUsersPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TotalUsersIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_group_50px.png"))); // NOI18N
        TotalUsersPanel.add(TotalUsersIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 40));

        UsersAmount.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        UsersAmount.setForeground(new java.awt.Color(51, 51, 51));
        UsersAmount.setText("1000");
        TotalUsersPanel.add(UsersAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 90, 20));

        TotalUsersTitleLabel.setForeground(new java.awt.Color(102, 102, 102));
        TotalUsersTitleLabel.setText("Total Users");
        TotalUsersPanel.add(TotalUsersTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        OverviewLayoutPanel.add(TotalUsersPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 230, 80));

        RatingPanel.setBackground(new java.awt.Color(255, 255, 255));
        RatingPanel.setRoundBottomLeft(15);
        RatingPanel.setRoundBottomRight(15);
        RatingPanel.setRoundTopLeft(15);
        RatingPanel.setRoundTopRight(15);
        RatingPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RatingAmount.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        RatingAmount.setForeground(new java.awt.Color(51, 51, 51));
        RatingAmount.setText("4.5");
        RatingPanel.add(RatingAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 40, 20));

        RatingTitleLabel.setForeground(new java.awt.Color(102, 102, 102));
        RatingTitleLabel.setText("Rating");
        RatingPanel.add(RatingTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        RatingIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_star_50px.png"))); // NOI18N
        RatingPanel.add(RatingIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 40));

        OverviewLayoutPanel.add(RatingPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 230, 80));

        CardLayoutSpace.add(OverviewLayoutPanel, "card4");

        DetailPostLayout.setBackground(new java.awt.Color(238, 238, 238));
        DetailPostLayout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SmallDPPanel.setBackground(new java.awt.Color(255, 255, 255));
        SmallDPPanel.setRoundBottomLeft(15);
        SmallDPPanel.setRoundBottomRight(15);
        SmallDPPanel.setRoundTopLeft(15);
        SmallDPPanel.setRoundTopRight(15);
        SmallDPPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Submit.setBorder(null);
        Submit.setForeground(new java.awt.Color(51, 51, 51));
        Submit.setText("Submit");
        Submit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Submit.setkBackGroundColor(new java.awt.Color(51, 51, 51));
        Submit.setkEndColor(new java.awt.Color(51, 51, 51));
        Submit.setkHoverEndColor(new java.awt.Color(102, 102, 102));
        Submit.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        Submit.setkHoverStartColor(new java.awt.Color(102, 102, 102));
        Submit.setkStartColor(new java.awt.Color(51, 51, 51));
        Submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitMouseClicked(evt);
            }
        });
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        SmallDPPanel.add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 480, 120, 40));

        PostImage.setText("Image Here");
        SmallDPPanel.add(PostImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 320, 350));

        PostContentScrollPane.setBorder(null);

        PostContent.setEditable(false);
        PostContent.setColumns(20);
        PostContent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PostContent.setForeground(new java.awt.Color(51, 51, 51));
        PostContent.setRows(5);
        PostContent.setText("Content Here\n");
        PostContent.setBorder(null);
        PostContentScrollPane.setViewportView(PostContent);

        SmallDPPanel.add(PostContentScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 520, 330));

        PostTitleScrollPane.setBorder(null);

        PostTitle.setEditable(false);
        PostTitle.setColumns(20);
        PostTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        PostTitle.setForeground(new java.awt.Color(51, 51, 51));
        PostTitle.setRows(2);
        PostTitle.setText("Tittle Here");
        PostTitle.setBorder(null);
        PostTitleScrollPane.setViewportView(PostTitle);

        SmallDPPanel.add(PostTitleScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 860, 70));

        DetailPostLayout.add(SmallDPPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 930, 560));

        CardLayoutSpace.add(DetailPostLayout, "card2");

        PostsLayoutPanel.setBackground(new java.awt.Color(238, 238, 238));
        PostsLayoutPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SmallPostPanel.setBackground(new java.awt.Color(255, 255, 255));
        SmallPostPanel.setPreferredSize(new java.awt.Dimension(920, 540));
        SmallPostPanel.setRoundBottomLeft(15);
        SmallPostPanel.setRoundBottomRight(15);
        SmallPostPanel.setRoundTopLeft(15);
        SmallPostPanel.setRoundTopRight(15);
        SmallPostPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AcceptBtn.setBorder(null);
        AcceptBtn.setForeground(new java.awt.Color(51, 51, 51));
        AcceptBtn.setText("Accept");
        AcceptBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AcceptBtn.setkBackGroundColor(new java.awt.Color(51, 51, 51));
        AcceptBtn.setkEndColor(new java.awt.Color(51, 51, 51));
        AcceptBtn.setkHoverEndColor(new java.awt.Color(102, 102, 102));
        AcceptBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        AcceptBtn.setkHoverStartColor(new java.awt.Color(102, 102, 102));
        AcceptBtn.setkStartColor(new java.awt.Color(51, 51, 51));
        AcceptBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AcceptBtnMouseClicked(evt);
            }
        });
        AcceptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptBtnActionPerformed(evt);
            }
        });
        SmallPostPanel.add(AcceptBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 490, 120, 40));

        PostTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PostTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "POSTID", "POSTTITLE", "POSTAUTHOR", "UPLOADDAY", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PostTable.setToolTipText("");
        PostTable.setFocusable(false);
        PostTable.setGridColor(new java.awt.Color(255, 255, 255));
        PostTable.setRowHeight(30);
        PostTable.setSelectionForeground(new java.awt.Color(0, 0, 0));
        PostTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PostTableMouseClicked(evt);
            }
        });
        PostTableScrollPane.setViewportView(PostTable);

        SmallPostPanel.add(PostTableScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 870, 450));

        DeleteButton.setBorder(null);
        DeleteButton.setForeground(new java.awt.Color(51, 51, 51));
        DeleteButton.setText("Delete");
        DeleteButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DeleteButton.setkBackGroundColor(new java.awt.Color(51, 51, 51));
        DeleteButton.setkEndColor(new java.awt.Color(51, 51, 51));
        DeleteButton.setkHoverEndColor(new java.awt.Color(102, 102, 102));
        DeleteButton.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        DeleteButton.setkHoverStartColor(new java.awt.Color(102, 102, 102));
        DeleteButton.setkStartColor(new java.awt.Color(51, 51, 51));
        DeleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteButtonMouseClicked(evt);
            }
        });
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });
        SmallPostPanel.add(DeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 490, 120, 40));

        PostsLayoutPanel.add(SmallPostPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        CardLayoutSpace.add(PostsLayoutPanel, "card3");

        AccountsLayoutPanel.setBackground(new java.awt.Color(238, 238, 238));
        AccountsLayoutPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SmallAccountPanel.setBackground(new java.awt.Color(255, 255, 255));
        SmallAccountPanel.setMinimumSize(new java.awt.Dimension(870, 540));
        SmallAccountPanel.setPreferredSize(new java.awt.Dimension(870, 540));
        SmallAccountPanel.setRoundBottomLeft(15);
        SmallAccountPanel.setRoundBottomRight(15);
        SmallAccountPanel.setRoundTopLeft(15);
        SmallAccountPanel.setRoundTopRight(15);
        SmallAccountPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AccountTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AccountTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Username", "Fullname", "PhoneNumber"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        AccountTable.setToolTipText("");
        AccountTable.setFocusable(false);
        AccountTable.setGridColor(new java.awt.Color(255, 255, 255));
        AccountTable.setRowHeight(30);
        AccountTable.setSelectionForeground(new java.awt.Color(0, 0, 0));
        AccountTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccountTableMouseClicked(evt);
            }
        });
        AccountTableSrcollPane.setViewportView(AccountTable);

        SmallAccountPanel.add(AccountTableSrcollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 860, 450));

        kButton1.setBorder(null);
        kButton1.setForeground(new java.awt.Color(51, 51, 51));
        kButton1.setText("Delete");
        kButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kButton1.setkBackGroundColor(new java.awt.Color(51, 51, 51));
        kButton1.setkEndColor(new java.awt.Color(51, 51, 51));
        kButton1.setkHoverEndColor(new java.awt.Color(102, 102, 102));
        kButton1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton1.setkHoverStartColor(new java.awt.Color(102, 102, 102));
        kButton1.setkStartColor(new java.awt.Color(51, 51, 51));
        kButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kButton1MouseClicked(evt);
            }
        });
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        SmallAccountPanel.add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 480, 120, 40));

        AccountsLayoutPanel.add(SmallAccountPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 930, -1));

        CardLayoutSpace.add(AccountsLayoutPanel, "card2");

        MainPanel.add(CardLayoutSpace, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 1020, 600));

        getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        RightColorPanel2.setVisible(false);
        RightColorPanel3.setVisible(false);
        RightColorPanel1.setVisible(true);
        OverviewPanel.setBackground(new Color(51, 51, 51));
        flexVisiblePanel1(RightColorPanel1);

        dtm1 = (DefaultTableModel) AccountTable.getModel();
        dtm2 = (DefaultTableModel) PostTable.getModel();
        

    }//GEN-LAST:event_formWindowOpened

    private void InputSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputSearchFocusGained
        if (InputSearch.getText().equals("Search content..")) {
            InputSearch.setText("");

        }
    }//GEN-LAST:event_InputSearchFocusGained

    private void InputSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputSearchFocusLost
        if (InputSearch.getText().equals("")) {
            InputSearch.setText("Search content..");

        }
    }//GEN-LAST:event_InputSearchFocusLost

    private void InputSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputSearchActionPerformed

    private void CardLayoutSpaceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CardLayoutSpaceFocusGained

    }//GEN-LAST:event_CardLayoutSpaceFocusGained

    private void CardLayoutSpaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CardLayoutSpaceMouseClicked

        disableFocusText(CardLayoutSpace, InputSearch);

    }//GEN-LAST:event_CardLayoutSpaceMouseClicked

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        setLocation(MouseInfo.getPointerInfo().getLocation());
    }//GEN-LAST:event_formMouseDragged

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void HomeLinkLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeLinkLabelMouseEntered
        HomeLinkPanel.setBackground(new Color(60, 63, 65));
    }//GEN-LAST:event_HomeLinkLabelMouseEntered

    private void HomeLinkLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeLinkLabelMouseExited
        HomeLinkPanel.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_HomeLinkLabelMouseExited

    private void HomeLinkLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeLinkLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeLinkLabelMouseClicked

    private void SettingLinkLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingLinkLabelMouseEntered
        SettingLinkPanel.setBackground(new Color(60, 63, 65));
    }//GEN-LAST:event_SettingLinkLabelMouseEntered

    private void SettingLinkLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingLinkLabelMouseExited
        SettingLinkPanel.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_SettingLinkLabelMouseExited

    private void SettingLinkLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingLinkLabelMouseClicked
        // TODO add your handling code here:
        close();
        UserProfilePage pro = new UserProfilePage();
        pro.setVisible(true);
    }//GEN-LAST:event_SettingLinkLabelMouseClicked

    private void CateLinkLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CateLinkLabelMouseEntered
        CateLinkPanel.setBackground(new Color(60, 63, 65));
    }//GEN-LAST:event_CateLinkLabelMouseEntered

    private void CateLinkLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CateLinkLabelMouseExited
        CateLinkPanel.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_CateLinkLabelMouseExited

    private void CateLinkLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CateLinkLabelMouseClicked


    }//GEN-LAST:event_CateLinkLabelMouseClicked

    private void OverviewTitleLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OverviewTitleLabelMouseEntered
        if (RightColorPanel1.isVisible() == false) {
            OverviewPanel.setBackground(new Color(51, 51, 51));
        }
    }//GEN-LAST:event_OverviewTitleLabelMouseEntered

    private void OverviewTitleLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OverviewTitleLabelMouseExited
        if (RightColorPanel1.isVisible() == false) {
            OverviewPanel.setBackground(new Color(35, 35, 35));
        }
    }//GEN-LAST:event_OverviewTitleLabelMouseExited

    private void OverviewTitleLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OverviewTitleLabelMouseClicked
        RightColorPanel1.setVisible(true);
        RightColorPanel2.setVisible(false);
        RightColorPanel3.setVisible(false);
        OverviewPanel.setBackground(new Color(51, 51, 51));
        AccountsPanel.setBackground(new Color(35, 35, 35));
        PostsPanel.setBackground(new Color(35, 35, 35));
        flexVisiblePanel1(RightColorPanel1);
        VisibleCount2 = 0;
        VisibleCount3 = 0;
        VisibleCount4 = 0;

        changePage(CardLayoutSpace, OverviewLayoutPanel);

    }//GEN-LAST:event_OverviewTitleLabelMouseClicked

    private void OverviewPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OverviewPanelMouseEntered
        if (RightColorPanel1.isVisible() == false) {
            OverviewPanel.setBackground(new Color(51, 51, 51));
        }
    }//GEN-LAST:event_OverviewPanelMouseEntered

    private void OverviewPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OverviewPanelMouseExited
        if (RightColorPanel1.isVisible() == false) {
            OverviewPanel.setBackground(new Color(35, 35, 35));
        }


    }//GEN-LAST:event_OverviewPanelMouseExited

    private void OverviewPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OverviewPanelMouseClicked
        page = 1;
        RightColorPanel1.setVisible(true);
        RightColorPanel2.setVisible(false);
        RightColorPanel3.setVisible(false);
        OverviewPanel.setBackground(new Color(51, 51, 51));
        AccountsPanel.setBackground(new Color(35, 35, 35));
        PostsPanel.setBackground(new Color(35, 35, 35));
        flexVisiblePanel1(RightColorPanel1);
        VisibleCount2 = 0;
        VisibleCount3 = 0;
        VisibleCount4 = 0;
        SearchBorderPanel.setVisible(false);
        changePage(CardLayoutSpace, OverviewLayoutPanel);
    }//GEN-LAST:event_OverviewPanelMouseClicked

    private void AccountsTitleLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountsTitleLabelMouseEntered
        if (RightColorPanel2.isVisible() == false) {
            AccountsPanel.setBackground(new Color(51, 51, 51));
        }
    }//GEN-LAST:event_AccountsTitleLabelMouseEntered

    private void AccountsTitleLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountsTitleLabelMouseExited
        if (RightColorPanel2.isVisible() == false) {
            AccountsPanel.setBackground(new Color(35, 35, 35));
        }
    }//GEN-LAST:event_AccountsTitleLabelMouseExited

    private void AccountsTitleLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountsTitleLabelMouseClicked
        RightColorPanel1.setVisible(false);
        RightColorPanel2.setVisible(true);
        RightColorPanel3.setVisible(false);
        AccountsPanel.setBackground(new Color(51, 51, 51));
        OverviewPanel.setBackground(new Color(35, 35, 35));
        PostsPanel.setBackground(new Color(35, 35, 35));
        flexVisiblePanel2(RightColorPanel2);
        VisibleCount1 = 0;
        VisibleCount3 = 0;
        VisibleCount4 = 0;

        changePage(CardLayoutSpace, AccountsLayoutPanel);
    }//GEN-LAST:event_AccountsTitleLabelMouseClicked

    private void AccountsPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountsPanelMouseEntered
        if (RightColorPanel2.isVisible() == false) {
            AccountsPanel.setBackground(new Color(51, 51, 51));
        }
    }//GEN-LAST:event_AccountsPanelMouseEntered

    private void AccountsPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountsPanelMouseExited
        if (RightColorPanel2.isVisible() == false) {
            AccountsPanel.setBackground(new Color(35, 35, 35));
        }
    }//GEN-LAST:event_AccountsPanelMouseExited

    private void AccountsPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountsPanelMouseClicked
        page = 2;
        RightColorPanel1.setVisible(false);
        RightColorPanel2.setVisible(true);
        RightColorPanel3.setVisible(false);
        AccountsPanel.setBackground(new Color(51, 51, 51));
        OverviewPanel.setBackground(new Color(35, 35, 35));
        PostsPanel.setBackground(new Color(35, 35, 35));
        flexVisiblePanel2(RightColorPanel2);
        VisibleCount1 = 0;
        VisibleCount3 = 0;
        VisibleCount4 = 0;
        SearchBorderPanel.setVisible(true);
        changePage(CardLayoutSpace, AccountsLayoutPanel);
        logindto.getAllAuthor(tblUser, "");
    }//GEN-LAST:event_AccountsPanelMouseClicked

    private void PostsTitleLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PostsTitleLabelMouseEntered
        if (RightColorPanel3.isVisible() == false) {
            PostsPanel.setBackground(new Color(51, 51, 51));
        }
    }//GEN-LAST:event_PostsTitleLabelMouseEntered

    private void PostsTitleLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PostsTitleLabelMouseExited
        if (RightColorPanel3.isVisible() == false) {
            PostsPanel.setBackground(new Color(35, 35, 35));
        }
    }//GEN-LAST:event_PostsTitleLabelMouseExited

    private void PostsTitleLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PostsTitleLabelMouseClicked
        RightColorPanel1.setVisible(false);
        RightColorPanel2.setVisible(false);
        RightColorPanel3.setVisible(true);
        AccountsPanel.setBackground(new Color(35, 35, 35));
        OverviewPanel.setBackground(new Color(35, 35, 35));
        PostsPanel.setBackground(new Color(51, 51, 51));
        flexVisiblePanel3(RightColorPanel3);
        VisibleCount1 = 0;
        VisibleCount2 = 0;
        VisibleCount4 = 0;

        changePage(CardLayoutSpace, PostsLayoutPanel);
    }//GEN-LAST:event_PostsTitleLabelMouseClicked

    private void PostsPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PostsPanelMouseEntered
        if (RightColorPanel3.isVisible() == false) {
            PostsPanel.setBackground(new Color(51, 51, 51));
        }
    }//GEN-LAST:event_PostsPanelMouseEntered

    private void PostsPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PostsPanelMouseExited
        if (RightColorPanel3.isVisible() == false) {
            PostsPanel.setBackground(new Color(35, 35, 35));
        }
    }//GEN-LAST:event_PostsPanelMouseExited

    private void PostsPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PostsPanelMouseClicked
        page = 3;
        RightColorPanel1.setVisible(false);
        RightColorPanel2.setVisible(false);
        RightColorPanel3.setVisible(true);
        AccountsPanel.setBackground(new Color(35, 35, 35));
        OverviewPanel.setBackground(new Color(35, 35, 35));
        PostsPanel.setBackground(new Color(51, 51, 51));
        flexVisiblePanel3(RightColorPanel3);
        VisibleCount1 = 0;
        VisibleCount2 = 0;
        VisibleCount4 = 0;
        changePage(CardLayoutSpace, PostsLayoutPanel);
        SearchBorderPanel.setVisible(true);
        articledto.getArticlePending("", tblArticle);
    }//GEN-LAST:event_PostsPanelMouseClicked

    private void ExitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtnMouseClicked
        close();
    }//GEN-LAST:event_ExitBtnMouseClicked

    private void AccountTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountTableMouseClicked
        index = AccountTable.getSelectedRow();
        convertArticle();
        //dua thong tin len trang detail
    }//GEN-LAST:event_AccountTableMouseClicked

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton1ActionPerformed

    private void AcceptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AcceptBtnActionPerformed

    private void PostTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PostTableMouseClicked
        if (evt.getClickCount() == 2) {
            changePage(CardLayoutSpace, DetailPostLayout);
        }
        PostContent.setLineWrap(true);
        PostContent.setWrapStyleWord(true);
        PostTitle.setLineWrap(true);
        PostTitle.setWrapStyleWord(true);
        DefaultTableModel b = new DefaultTableModel();
        String a =  (String) PostTable.getModel().getValueAt(PostTable.getSelectedRow(), 0);
        System.out.println("wss: "+a);
        articledto.privateAddDetail(PostTitle, PostContent, PostImage, Integer.parseInt(a));
    }//GEN-LAST:event_PostTableMouseClicked

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitActionPerformed

    private void HomeLinkPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeLinkPanelMouseClicked
        // TODO add your handling code here:\
        close();
    }//GEN-LAST:event_HomeLinkPanelMouseClicked

    private void InputSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InputSearchMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_InputSearchMouseClicked

    private void AcceptBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcceptBtnMouseClicked
        // TODO add your handling code here:
        browseArticle("done");
    }//GEN-LAST:event_AcceptBtnMouseClicked

    private void DeleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteButtonMouseClicked
        // TODO add your handling code here:
        browseArticle("fail");
    }//GEN-LAST:event_DeleteButtonMouseClicked

    private void kButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton1MouseClicked
        // TODO add your handling code here:
        deleteUser();
    }//GEN-LAST:event_kButton1MouseClicked

    private void SubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseClicked
        // TODO add your handling code here:
        page = 3;
        RightColorPanel1.setVisible(false);
        RightColorPanel2.setVisible(false);
        RightColorPanel3.setVisible(true);
        AccountsPanel.setBackground(new Color(35, 35, 35));
        OverviewPanel.setBackground(new Color(35, 35, 35));
        PostsPanel.setBackground(new Color(51, 51, 51));
        flexVisiblePanel3(RightColorPanel3);
        VisibleCount1 = 0;
        VisibleCount2 = 0;
        VisibleCount4 = 0;
        changePage(CardLayoutSpace, PostsLayoutPanel);
        browseArticle("done");
    }//GEN-LAST:event_SubmitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    public void close() {
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }

    int VisibleCount1 = 0;
    int VisibleCount2 = 0;
    int VisibleCount3 = 0;
    int VisibleCount4 = 0;
    DefaultTableModel dtm1;
    DefaultTableModel dtm2;
    int index = 0;
    
    public void initObject(){
        ArrayList<Article> at = articledto.Top2View();
        articledto.setImagePage(at.get(0).getImage(), Top1PostImage);
        articledto.setImagePage(at.get(1).getImage(), Top2PostImage);
        Top1PostTitle.setText(at.get(0).getTitle());
        Top2PostTitle.setText(at.get(1).getTitle());
        AuthorUsername1.setText(at.get(0).getAuthor());
        AuthorUsername2.setText(at.get(1).getAuthor());
        SearchBorderPanel.setVisible(false);
        PostsAmount.setText(String.valueOf(articledto.getAmount()));
        UsersAmount.setText(String.valueOf(logindto.amount_user)+1);
        initTable();
    }
    
    public void initTable(){
        String[] columnContent1 = new String[]{"ID", "UserName", "FullName", "Phone Number","Amount Articles"};

        tblUser = new DefaultTableModel(){
      
          @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblUser.setColumnIdentifiers(columnContent1);
        AccountTable.setModel(tblUser);
        
        String[] columnContent2 = new String[]{"PostCode", "PostTittle", "Comments","PostAuthor", "UploadDay"};

        tblArticle = new DefaultTableModel(){
      
          @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblArticle.setColumnIdentifiers(columnContent2);
        PostTable.setModel(tblArticle);
        
    }

    public void flexVisiblePanel1(JPanel panel) {
        if (VisibleCount1 == 0) {

            panel.setVisible(true);
            VisibleCount1++;
        }
    }

    public void flexVisiblePanel2(JPanel panel) {
        if (VisibleCount2 == 0) {

            panel.setVisible(true);
            VisibleCount2++;
        }
    }

    public void flexVisiblePanel3(JPanel panel) {
        if (VisibleCount3 == 0) {

            panel.setVisible(true);
            VisibleCount3++;
        }
    }

    public void flexVisiblePanel4(JPanel panel) {
        if (VisibleCount4 == 0) {

            panel.setVisible(true);
            VisibleCount4++;
        }
    }

    public void disableFocusText(JPanel panel, JTextField textField) {
        if (textField.getText().equals("")) {
            textField.setText("Search content..");
            panel.requestFocusInWindow();
        } else {
            panel.requestFocusInWindow();
        }
    }

    public void changePage(JPanel layoutPanel, JPanel pagePanel) {
        layoutPanel.removeAll();
        layoutPanel.add(pagePanel);
        layoutPanel.repaint();
        layoutPanel.revalidate();
    }
    
    public void search(){
        if(page == 2){
            logindto.getAllAuthor(tblUser, InputSearch.getText());
        }
        else if(page == 3){
            articledto.searchArticle(tblArticle, InputSearch.getText(), "pending");
        }
        InputSearch.setText("");
    }
    
    public void convertArticle(){
        int a =  (int) AccountTable.getModel().getValueAt(AccountTable.getSelectedRow(), 4);
        if(a < 1){
            JOptionPane.showMessageDialog(this, "This user don't have any article");
        }else {
            String b = (String) AccountTable.getModel().getValueAt(AccountTable.getSelectedRow(), 1);
            articledto.getArticlePending(b, tblArticle);
            RightColorPanel1.setVisible(false);
            RightColorPanel2.setVisible(false);
            RightColorPanel3.setVisible(true);
            AccountsPanel.setBackground(new Color(35, 35, 35));
            OverviewPanel.setBackground(new Color(35, 35, 35));
            PostsPanel.setBackground(new Color(51, 51, 51));
            flexVisiblePanel3(RightColorPanel3);
            VisibleCount1 = 0;
            VisibleCount2 = 0;
            VisibleCount4 = 0;
            changePage(CardLayoutSpace, PostsLayoutPanel);
        }
        
    }
    
    public void browseArticle(String state){
        int input = JOptionPane.showConfirmDialog(null, 
                    "Do you want to proceed?", "Select an Option...",JOptionPane.YES_NO_CANCEL_OPTION);
        
        if(input==0){
            String a =  (String) PostTable.getModel().getValueAt(PostTable.getSelectedRow(), 0);
            articledto.browseArticle(String.valueOf(logindto.makeId()), a, state);
            articledto.getArticlePending("", tblArticle);
        }

    }

    public void deleteUser(){
        if(logindto.checkRole().equals("user")){
            int input = JOptionPane.showConfirmDialog(null, 
                    "Do you want to proceed?", "Select an Option...",JOptionPane.YES_NO_CANCEL_OPTION);
            if(input==0){
                String a =  (String) AccountTable.getModel().getValueAt(AccountTable.getSelectedRow(), 0);
                logindto.deleteUser(a);
                logindto.getAllAuthor(tblUser, "");
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "You unable to delete this user.");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton AcceptBtn;
    private javax.swing.JTable AccountTable;
    private javax.swing.JScrollPane AccountTableSrcollPane;
    private javax.swing.JPanel AccountsLayoutPanel;
    private Test.JPanelRounded AccountsPanel;
    private javax.swing.JLabel AccountsTitleLabel;
    private javax.swing.JLabel AuthorUsername1;
    private javax.swing.JLabel AuthorUsername2;
    private javax.swing.JPanel CardLayoutSpace;
    private javax.swing.JLabel CateLinkLabel;
    private javax.swing.JPanel CateLinkPanel;
    private com.k33ptoo.components.KButton DeleteButton;
    private javax.swing.JPanel DetailPostLayout;
    private javax.swing.JLabel ExitBtn;
    private javax.swing.JLabel HomeLinkLabel;
    private javax.swing.JPanel HomeLinkPanel;
    private javax.swing.JTextField InputSearch;
    private javax.swing.JPanel LeftMenuPanel;
    private com.k33ptoo.components.KGradientPanel MainPanel;
    private javax.swing.JPanel OverviewLayoutPanel;
    private Test.JPanelRounded OverviewPanel;
    private javax.swing.JLabel OverviewTitleLabel;
    private javax.swing.JTextArea PostContent;
    private javax.swing.JScrollPane PostContentScrollPane;
    private javax.swing.JLabel PostImage;
    private javax.swing.JTable PostTable;
    private javax.swing.JScrollPane PostTableScrollPane;
    private javax.swing.JTextArea PostTitle;
    private javax.swing.JScrollPane PostTitleScrollPane;
    private javax.swing.JLabel PostsAmount;
    private javax.swing.JPanel PostsLayoutPanel;
    private Test.JPanelRounded PostsPanel;
    private javax.swing.JLabel PostsTitleLabel;
    private javax.swing.JLabel RatingAmount;
    private javax.swing.JLabel RatingIcon;
    private Test.JPanelRounded RatingPanel;
    private javax.swing.JLabel RatingTitleLabel;
    private Test.JPanelRounded RightColorPanel1;
    private Test.JPanelRounded RightColorPanel2;
    private Test.JPanelRounded RightColorPanel3;
    private javax.swing.JPanel SearchBorderPanel;
    private javax.swing.JLabel SettingLinkLabel;
    private javax.swing.JPanel SettingLinkPanel;
    private Test.JPanelRounded SmallAccountPanel;
    private Test.JPanelRounded SmallDPPanel;
    private Test.JPanelRounded SmallOverviewPanel;
    private Test.JPanelRounded SmallPostPanel;
    private com.k33ptoo.components.KButton Submit;
    private javax.swing.JLabel TipsLabel;
    private javax.swing.JLabel Top1PostImage;
    private javax.swing.JLabel Top1PostTitle;
    private javax.swing.JLabel Top2PostImage;
    private javax.swing.JLabel Top2PostTitle;
    private javax.swing.JPanel TopMenuPanel1;
    private javax.swing.JPanel TopMenuPanel2;
    private javax.swing.JLabel TopPostMonthTitle;
    private javax.swing.JLabel TotalPostIcon;
    private javax.swing.JLabel TotalPostTitleLabel;
    private Test.JPanelRounded TotalPostsPanel;
    private javax.swing.JLabel TotalUsersIcon;
    private Test.JPanelRounded TotalUsersPanel;
    private javax.swing.JLabel TotalUsersTitleLabel;
    private javax.swing.JLabel UsersAmount;
    private javax.swing.JLabel jLabel3;
    private com.k33ptoo.components.KButton kButton1;
    // End of variables declaration//GEN-END:variables
}
