/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import java.awt.Color;

/**
 *
 * @author ASUS
 */
public class SignUpPageForTesting extends javax.swing.JDialog {

    /**
     * Creates new form SignUpPag
     */
    public SignUpPageForTesting(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        ChooseAvatar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        InputUsername = new javax.swing.JTextField();
        InputPassword = new javax.swing.JTextField();
        InputName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        kButton1 = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(204, 0, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 102, 102));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(1000, 700));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ChooseAvatar.setBackground(new Color(0,0,0,0));
        ChooseAvatar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ChooseAvatar.setForeground(new java.awt.Color(153, 153, 153));
        ChooseAvatar.setText("      Choose your avatar");
        ChooseAvatar.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        ChooseAvatar.setEnabled(false);
        ChooseAvatar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ChooseAvatarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ChooseAvatarFocusLost(evt);
            }
        });
        ChooseAvatar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseAvatarActionPerformed(evt);
            }
        });
        kGradientPanel1.add(ChooseAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, 450, 60));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Welcome");
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 220, 70));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Let's sign you up quickly");
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 270, -1));

        InputUsername.setBackground(new Color(0,0,0,0));
        InputUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        InputUsername.setForeground(new java.awt.Color(153, 153, 153));
        InputUsername.setText("      Enter username");
        InputUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        InputUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InputUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                InputUsernameFocusLost(evt);
            }
        });
        InputUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputUsernameActionPerformed(evt);
            }
        });
        kGradientPanel1.add(InputUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 450, 60));

        InputPassword.setBackground(new Color(0,0,0,0));
        InputPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        InputPassword.setForeground(new java.awt.Color(153, 153, 153));
        InputPassword.setText("      Enter password");
        InputPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        InputPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InputPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                InputPasswordFocusLost(evt);
            }
        });
        InputPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputPasswordActionPerformed(evt);
            }
        });
        kGradientPanel1.add(InputPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 450, 60));

        InputName.setBackground(new Color(0,0,0,0));
        InputName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        InputName.setForeground(new java.awt.Color(153, 153, 153));
        InputName.setText("      Enter your name");
        InputName.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        InputName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InputNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                InputNameFocusLost(evt);
            }
        });
        InputName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputNameActionPerformed(evt);
            }
        });
        kGradientPanel1.add(InputName, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 450, 60));

        jLabel1.setBackground(new Color(0, 0, 0)
        );
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sign Up");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 3, new java.awt.Color(102, 102, 102)));
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setPreferredSize(new java.awt.Dimension(950, 48));
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 319, 720));

        kButton1.setForeground(new java.awt.Color(0, 0, 0));
        kButton1.setText("SUBMIT");
        kButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        kButton1.setkBorderRadius(0);
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 610, 170, 50));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -20, 1030, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChooseAvatarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseAvatarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChooseAvatarActionPerformed

    private void ChooseAvatarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ChooseAvatarFocusGained

    }//GEN-LAST:event_ChooseAvatarFocusGained

    private void ChooseAvatarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ChooseAvatarFocusLost

    }//GEN-LAST:event_ChooseAvatarFocusLost

    private void InputUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputUsernameFocusGained
        if (InputUsername.getText().equals("      Enter username")) {
            InputUsername.setText("");
            InputUsername.setForeground(new Color(255, 255, 255));
        }
    }//GEN-LAST:event_InputUsernameFocusGained

    private void InputUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputUsernameFocusLost
        if (InputUsername.getText().equals("")) {
            InputUsername.setText("      Enter username");
            InputUsername.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_InputUsernameFocusLost

    private void InputUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputUsernameActionPerformed

    private void InputPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputPasswordFocusGained
        if (InputPassword.getText().equals("      Enter password")) {
            InputPassword.setText("");
            InputPassword.setForeground(new Color(255, 255, 255));
        }
    }//GEN-LAST:event_InputPasswordFocusGained

    private void InputPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputPasswordFocusLost
        if (InputPassword.getText().equals("")) {
            InputPassword.setText("      Enter password");
            InputPassword.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_InputPasswordFocusLost

    private void InputPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputPasswordActionPerformed

    private void InputNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputNameFocusGained
         if (InputName.getText().equals("      Enter your name")) {
            InputName.setText("");
            InputName.setForeground(new Color(255, 255, 255));
        }
    }//GEN-LAST:event_InputNameFocusGained

    private void InputNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputNameFocusLost
        if (InputName.getText().equals("")) {
            InputName.setText("      Enter your name");
            InputName.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_InputNameFocusLost

    private void InputNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputNameActionPerformed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpPageForTesting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpPageForTesting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpPageForTesting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpPageForTesting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SignUpPageForTesting dialog = new SignUpPageForTesting(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ChooseAvatar;
    private javax.swing.JTextField InputName;
    private javax.swing.JTextField InputPassword;
    private javax.swing.JTextField InputUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private com.k33ptoo.components.KButton kButton1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
