/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;


import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.awt.geom.RoundRectangle2D;


/**
 *
 * @author ASUS
 */
public class UserProfilePage extends javax.swing.JFrame {

    /**
     * Creates new form UserProfilePage
     */
    public UserProfilePage() {
        initComponents();
        setLocationRelativeTo(null);
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 20, 20));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new com.k33ptoo.components.KGradientPanel();
        SaveBtn = new com.k33ptoo.components.KButton();
        TitleLabel = new javax.swing.JLabel();
        ExitButton = new javax.swing.JLabel();
        PasswordPanel = new javax.swing.JPanel();
        PasswordLabel = new javax.swing.JLabel();
        InputPassword = new javax.swing.JTextField();
        UsernamePanel = new javax.swing.JPanel();
        UsernameLabel = new javax.swing.JLabel();
        InputUsername = new javax.swing.JTextField();
        PNumberPanel = new javax.swing.JPanel();
        InputPhoneNumber = new javax.swing.JLabel();
        PNumberTF = new javax.swing.JTextField();
        NamePanel = new javax.swing.JPanel();
        NameLabel = new javax.swing.JLabel();
        InputName = new javax.swing.JTextField();
        ThumnailLabel = new javax.swing.JLabel();
        EmptyNotice = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(590, 540));
        setSize(new java.awt.Dimension(0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainPanel.setkBorderRadius(25);
        MainPanel.setkEndColor(new java.awt.Color(0, 0, 0));
        MainPanel.setkStartColor(new java.awt.Color(0, 0, 0));
        MainPanel.setPreferredSize(new java.awt.Dimension(700, 750));
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SaveBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 5, 1));
        SaveBtn.setText("Save");
        SaveBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        SaveBtn.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        SaveBtn.setkBorderRadius(45);
        SaveBtn.setkEndColor(new java.awt.Color(255, 255, 255));
        SaveBtn.setkForeGround(new java.awt.Color(0, 0, 0));
        SaveBtn.setkHoverColor(new java.awt.Color(0, 0, 0));
        SaveBtn.setkHoverEndColor(new java.awt.Color(0, 0, 0));
        SaveBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        SaveBtn.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        SaveBtn.setkSelectedColor(new java.awt.Color(255, 255, 255));
        SaveBtn.setkStartColor(new java.awt.Color(255, 255, 255));
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });
        MainPanel.add(SaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 80, 40));

        TitleLabel.setBackground(new java.awt.Color(0, 0, 0));
        TitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        TitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        TitleLabel.setText("Edit profile");
        MainPanel.add(TitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        ExitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_Close_20px_1.png"))); // NOI18N
        ExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitButtonMouseExited(evt);
            }
        });
        MainPanel.add(ExitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 30));

        PasswordPanel.setBackground(new java.awt.Color(0, 0, 0));
        PasswordPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        PasswordPanel.setForeground(new java.awt.Color(204, 204, 204));

        PasswordLabel.setForeground(new java.awt.Color(102, 102, 102));
        PasswordLabel.setText("Password");

        InputPassword.setBackground(new java.awt.Color(0, 0, 0));
        InputPassword.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        InputPassword.setForeground(new java.awt.Color(255, 255, 255));
        InputPassword.setBorder(null);
        InputPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PasswordPanelLayout = new javax.swing.GroupLayout(PasswordPanel);
        PasswordPanel.setLayout(PasswordPanelLayout);
        PasswordPanelLayout.setHorizontalGroup(
            PasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PasswordPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InputPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                    .addGroup(PasswordPanelLayout.createSequentialGroup()
                        .addComponent(PasswordLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PasswordPanelLayout.setVerticalGroup(
            PasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PasswordPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MainPanel.add(PasswordPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 550, 70));

        UsernamePanel.setBackground(new java.awt.Color(0, 0, 0));
        UsernamePanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        UsernamePanel.setForeground(new java.awt.Color(204, 204, 204));

        UsernameLabel.setForeground(new java.awt.Color(102, 102, 102));
        UsernameLabel.setText("Username");

        InputUsername.setBackground(new java.awt.Color(0, 0, 0));
        InputUsername.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        InputUsername.setForeground(new java.awt.Color(255, 255, 255));
        InputUsername.setBorder(null);
        InputUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputUsernameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UsernamePanelLayout = new javax.swing.GroupLayout(UsernamePanel);
        UsernamePanel.setLayout(UsernamePanelLayout);
        UsernamePanelLayout.setHorizontalGroup(
            UsernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsernamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UsernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InputUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                    .addGroup(UsernamePanelLayout.createSequentialGroup()
                        .addComponent(UsernameLabel)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        UsernamePanelLayout.setVerticalGroup(
            UsernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsernamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UsernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InputUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MainPanel.add(UsernamePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 550, 70));

        PNumberPanel.setBackground(new java.awt.Color(0, 0, 0));
        PNumberPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        PNumberPanel.setForeground(new java.awt.Color(204, 204, 204));

        InputPhoneNumber.setForeground(new java.awt.Color(102, 102, 102));
        InputPhoneNumber.setText("Phone number");

        PNumberTF.setBackground(new java.awt.Color(0, 0, 0));
        PNumberTF.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        PNumberTF.setForeground(new java.awt.Color(255, 255, 255));
        PNumberTF.setBorder(null);
        PNumberTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PNumberTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PNumberPanelLayout = new javax.swing.GroupLayout(PNumberPanel);
        PNumberPanel.setLayout(PNumberPanelLayout);
        PNumberPanelLayout.setHorizontalGroup(
            PNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNumberPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PNumberTF)
                    .addGroup(PNumberPanelLayout.createSequentialGroup()
                        .addComponent(InputPhoneNumber)
                        .addGap(0, 465, Short.MAX_VALUE))))
        );
        PNumberPanelLayout.setVerticalGroup(
            PNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNumberPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InputPhoneNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PNumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MainPanel.add(PNumberPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 550, 70));

        NamePanel.setBackground(new java.awt.Color(0, 0, 0));
        NamePanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        NamePanel.setForeground(new java.awt.Color(204, 204, 204));

        NameLabel.setForeground(new java.awt.Color(102, 102, 102));
        NameLabel.setText("Name");

        InputName.setBackground(new java.awt.Color(0, 0, 0));
        InputName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        InputName.setForeground(new java.awt.Color(255, 255, 255));
        InputName.setBorder(null);
        InputName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NamePanelLayout = new javax.swing.GroupLayout(NamePanel);
        NamePanel.setLayout(NamePanelLayout);
        NamePanelLayout.setHorizontalGroup(
            NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InputName, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                    .addGroup(NamePanelLayout.createSequentialGroup()
                        .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        NamePanelLayout.setVerticalGroup(
            NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InputName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MainPanel.add(NamePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 550, 70));

        ThumnailLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SunriseLake.png"))); // NOI18N
        ThumnailLabel.setText("jLabel1");
        MainPanel.add(ThumnailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 630, 130));

        EmptyNotice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EmptyNotice.setForeground(new java.awt.Color(255, 0, 0));
        EmptyNotice.setText("Please Don't Let Any Information Box Empty!");
        MainPanel.add(EmptyNotice, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, -1, -1));

        getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -20, 610, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        if (InputName.getText().equals("")) {
            EmptyNotice.setVisible(true);
        }
        else{
            EmptyNotice.setVisible(false);
        }
        if (PNumberTF.getText().equals("")) {
            EmptyNotice.setVisible(true);
        }
        else{
            EmptyNotice.setVisible(false);
        }
        if (InputUsername.getText().equals("")) {
            EmptyNotice.setVisible(true);
        }
        else{
            EmptyNotice.setVisible(false);
        }
        if (InputPassword.getText().equals("")) {
            EmptyNotice.setVisible(true);
        }
        else{
            EmptyNotice.setVisible(false);
        }
       
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void ExitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitButtonMouseEntered

    private void ExitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButtonMouseExited
        
    }//GEN-LAST:event_ExitButtonMouseExited

    private void ExitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButtonMouseClicked
        close();
    }//GEN-LAST:event_ExitButtonMouseClicked

    private void PNumberTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PNumberTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PNumberTFActionPerformed

    private void InputNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputNameActionPerformed

    private void InputUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputUsernameActionPerformed

    private void InputPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputPasswordActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        EmptyNotice.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserProfilePage().setVisible(true);
            }
        });
    }

    public void close() {
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    
 

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EmptyNotice;
    private javax.swing.JLabel ExitButton;
    private javax.swing.JTextField InputName;
    private javax.swing.JTextField InputPassword;
    private javax.swing.JLabel InputPhoneNumber;
    private javax.swing.JTextField InputUsername;
    private com.k33ptoo.components.KGradientPanel MainPanel;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JPanel NamePanel;
    private javax.swing.JPanel PNumberPanel;
    private javax.swing.JTextField PNumberTF;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JPanel PasswordPanel;
    private com.k33ptoo.components.KButton SaveBtn;
    private javax.swing.JLabel ThumnailLabel;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JPanel UsernamePanel;
    // End of variables declaration//GEN-END:variables
}
