/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Test;

import View.UserProfilePage;
import View.*;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author ASUS
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FramePanel = new com.k33ptoo.components.KGradientPanel();
        MenuLine1 = new javax.swing.JPanel();
        SayWelcome = new javax.swing.JPanel();
        WelcomeLabel = new javax.swing.JLabel();
        LogoLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        ExitPanel = new javax.swing.JPanel();
        ExitLabel = new javax.swing.JLabel();
        LogoutPanel = new javax.swing.JPanel();
        LogoutLabel = new javax.swing.JLabel();
        ProfileLabel = new javax.swing.JLabel();
        MenuLine2 = new javax.swing.JPanel();
        DashboardPanel = new javax.swing.JPanel();
        DashboardLabel = new javax.swing.JLabel();
        SearchInput = new javax.swing.JTextField();
        SearchBtn = new com.k33ptoo.components.KButton();
        NewPostPanel = new javax.swing.JPanel();
        NewPostLabel = new javax.swing.JLabel();
        AboutUsPanel = new javax.swing.JPanel();
        AboutUsLabel = new javax.swing.JLabel();
        CardLayoutPanel = new javax.swing.JPanel();
        HomeLayout = new javax.swing.JPanel();
        MainPostLabelPanel = new javax.swing.JPanel();
        TopicMainPost = new javax.swing.JLabel();
        MainLabelPost = new javax.swing.JLabel();
        MainThumbnail = new javax.swing.JLabel();
        LabelPost2 = new javax.swing.JLabel();
        Thumbnail2 = new javax.swing.JLabel();
        Thumbnail1 = new javax.swing.JLabel();
        LabelPost1 = new javax.swing.JLabel();
        DashboardLayout = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        AboutUsLayout = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        NewPostLayout = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        SearchLayout = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        PageDetailLayout = new javax.swing.JPanel();
        DetailPageTitle = new javax.swing.JLabel();
        PageDetailImage = new javax.swing.JLabel();
        CommentPanel = new javax.swing.JPanel();
        ConfirmBtn = new com.k33ptoo.components.KButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        CommentTable = new javax.swing.JTable();
        InputComment = new javax.swing.JTextField();
        GoBack = new javax.swing.JLabel();
        PageDetailContent = new javax.swing.JLabel();
        CommentBtn = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FramePanel.setkBorderRadius(0);
        FramePanel.setkEndColor(new java.awt.Color(255, 255, 255));
        FramePanel.setkStartColor(new java.awt.Color(255, 255, 255));
        FramePanel.setPreferredSize(new java.awt.Dimension(1920, 1080));
        FramePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuLine1.setBackground(new java.awt.Color(0, 0, 0));
        MenuLine1.setPreferredSize(new java.awt.Dimension(1920, 80));
        MenuLine1.setRequestFocusEnabled(false);
        MenuLine1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SayWelcome.setBackground(new java.awt.Color(0, 0, 0));
        SayWelcome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WelcomeLabel.setFont(new java.awt.Font("Segoe Script", 0, 20)); // NOI18N
        WelcomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        WelcomeLabel.setText("Welcome");
        SayWelcome.add(WelcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 200, 40));

        MenuLine1.add(SayWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 80));

        LogoLabel.setFont(new java.awt.Font("Lucida Calligraphy", 0, 40)); // NOI18N
        LogoLabel.setForeground(new java.awt.Color(255, 204, 204));
        LogoLabel.setText("RiToCon ");
        LogoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoLabelMouseClicked(evt);
            }
        });
        MenuLine1.add(LogoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 0, 0, new java.awt.Color(102, 102, 102)));
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        MenuLine1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 10, 10, 60));

        ExitPanel.setBackground(new java.awt.Color(0, 0, 0));
        ExitPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitPanelMouseExited(evt);
            }
        });
        ExitPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ExitLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ExitLabel.setForeground(new java.awt.Color(255, 255, 255));
        ExitLabel.setText("Exit");
        ExitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitLabelMouseExited(evt);
            }
        });
        ExitPanel.add(ExitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        MenuLine1.add(ExitPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 0, 80, 80));

        LogoutPanel.setBackground(new java.awt.Color(0, 0, 0));
        LogoutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutPanelMouseExited(evt);
            }
        });
        LogoutPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoutLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LogoutLabel.setForeground(new java.awt.Color(255, 255, 255));
        LogoutLabel.setText("Logout");
        LogoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutLabelMouseExited(evt);
            }
        });
        LogoutPanel.add(LogoutLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        MenuLine1.add(LogoutPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 0, 80, 80));

        ProfileLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        ProfileLabel.setForeground(new java.awt.Color(51, 51, 51));
        ProfileLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_male_user_50px.png"))); // NOI18N
        ProfileLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProfileLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ProfileLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ProfileLabelMouseExited(evt);
            }
        });
        MenuLine1.add(ProfileLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 20, -1, -1));

        FramePanel.add(MenuLine1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        MenuLine1.getAccessibleContext().setAccessibleName("");

        MenuLine2.setBackground(new java.awt.Color(255, 255, 255));
        MenuLine2.setPreferredSize(new java.awt.Dimension(1920, 90));
        MenuLine2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DashboardPanel.setBackground(new java.awt.Color(255, 255, 255));
        DashboardPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DashboardPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DashboardPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DashboardPanelMouseExited(evt);
            }
        });
        DashboardPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DashboardLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        DashboardLabel.setForeground(new java.awt.Color(51, 51, 51));
        DashboardLabel.setText("Dashboard");
        DashboardLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DashboardLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DashboardLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DashboardLabelMouseExited(evt);
            }
        });
        DashboardPanel.add(DashboardLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        MenuLine2.add(DashboardPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 120, 40));

        SearchInput.setBackground(new java.awt.Color(235, 235, 235));
        SearchInput.setForeground(new java.awt.Color(0, 0, 0));
        SearchInput.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        MenuLine2.add(SearchInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 50, 210, 40));

        SearchBtn.setText("Search");
        SearchBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SearchBtn.setkBackGroundColor(new java.awt.Color(51, 51, 51));
        SearchBtn.setkBorderRadius(50);
        SearchBtn.setkEndColor(new java.awt.Color(51, 51, 51));
        SearchBtn.setkHoverEndColor(new java.awt.Color(51, 51, 51));
        SearchBtn.setkHoverForeGround(new java.awt.Color(102, 102, 102));
        SearchBtn.setkHoverStartColor(new java.awt.Color(102, 102, 102));
        SearchBtn.setkSelectedColor(new java.awt.Color(102, 102, 102));
        SearchBtn.setkStartColor(new java.awt.Color(51, 51, 51));
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });
        MenuLine2.add(SearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 50, 110, 40));

        NewPostPanel.setBackground(new java.awt.Color(255, 255, 255));
        NewPostPanel.setForeground(new java.awt.Color(255, 255, 255));
        NewPostPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewPostPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NewPostPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NewPostPanelMouseExited(evt);
            }
        });
        NewPostPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NewPostLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        NewPostLabel.setForeground(new java.awt.Color(51, 51, 51));
        NewPostLabel.setText("New Post");
        NewPostLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewPostLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NewPostLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NewPostLabelMouseExited(evt);
            }
        });
        NewPostPanel.add(NewPostLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        MenuLine2.add(NewPostPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 110, 40));

        AboutUsPanel.setBackground(new java.awt.Color(255, 255, 255));
        AboutUsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutUsPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AboutUsPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AboutUsPanelMouseExited(evt);
            }
        });
        AboutUsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AboutUsLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        AboutUsLabel.setForeground(new java.awt.Color(51, 51, 51));
        AboutUsLabel.setText("About Us");
        AboutUsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutUsLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AboutUsLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AboutUsLabelMouseExited(evt);
            }
        });
        AboutUsPanel.add(AboutUsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        MenuLine2.add(AboutUsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 100, 40));

        FramePanel.add(MenuLine2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));

        CardLayoutPanel.setBackground(new java.awt.Color(255, 255, 255));
        CardLayoutPanel.setPreferredSize(new java.awt.Dimension(1920, 90));
        CardLayoutPanel.setLayout(new java.awt.CardLayout());

        HomeLayout.setBackground(new java.awt.Color(255, 255, 255));
        HomeLayout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainPostLabelPanel.setBackground(new java.awt.Color(220, 220, 220));
        MainPostLabelPanel.setForeground(new java.awt.Color(204, 204, 204));
        MainPostLabelPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TopicMainPost.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TopicMainPost.setForeground(new java.awt.Color(51, 51, 51));
        TopicMainPost.setText("NATURE LIFE");
        MainPostLabelPanel.add(TopicMainPost, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        MainLabelPost.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        MainLabelPost.setForeground(new java.awt.Color(0, 0, 0));
        MainLabelPost.setText("<html> Picture about a snow mountain  very fantastic for everybody </html>");
        MainPostLabelPanel.add(MainLabelPost, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 350, 130));

        HomeLayout.add(MainPostLabelPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 430, 210));

        MainThumbnail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thumb2.png"))); // NOI18N
        HomeLayout.add(MainThumbnail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 600, 440));

        LabelPost2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LabelPost2.setForeground(new java.awt.Color(0, 0, 0));
        LabelPost2.setText("<html>Windows 11 have some improvement about the performence of some game in many platform  </html>");
        LabelPost2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelPost2MouseClicked(evt);
            }
        });
        HomeLayout.add(LabelPost2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 410, 560, 70));

        Thumbnail2.setText("Image 2 here");
        HomeLayout.add(Thumbnail2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 270, 710, 140));

        Thumbnail1.setText("Image 1 here");
        HomeLayout.add(Thumbnail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 40, 710, 140));

        LabelPost1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LabelPost1.setForeground(new java.awt.Color(0, 0, 0));
        LabelPost1.setText("<html>Sunrise Lake is now available for tourise who want to checkin </html>");
        LabelPost1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelPost1MouseClicked(evt);
            }
        });
        HomeLayout.add(LabelPost1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 180, 560, 70));

        CardLayoutPanel.add(HomeLayout, "card2");

        DashboardLayout.setBackground(new java.awt.Color(255, 255, 255));
        DashboardLayout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("DASHBOARD");
        DashboardLayout.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, -1, -1));

        CardLayoutPanel.add(DashboardLayout, "card2");

        AboutUsLayout.setBackground(new java.awt.Color(255, 255, 255));
        AboutUsLayout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("We are a coder team with 4 people and we hope enjoy using our app ");
        AboutUsLayout.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, 150));

        CardLayoutPanel.add(AboutUsLayout, "card2");

        NewPostLayout.setBackground(new java.awt.Color(255, 255, 255));
        NewPostLayout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("NEW POST");
        NewPostLayout.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, -1, -1));

        CardLayoutPanel.add(NewPostLayout, "card2");

        SearchLayout.setBackground(new java.awt.Color(255, 255, 255));
        SearchLayout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Search");
        SearchLayout.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, -1, -1));

        CardLayoutPanel.add(SearchLayout, "card2");

        PageDetailLayout.setBackground(new java.awt.Color(255, 255, 255));
        PageDetailLayout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DetailPageTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        DetailPageTitle.setForeground(new java.awt.Color(0, 0, 0));
        DetailPageTitle.setText("Insert Page Title Here");
        PageDetailLayout.add(DetailPageTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, -1));

        PageDetailImage.setText("Image Here");
        PageDetailImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        PageDetailLayout.add(PageDetailImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 510, 460));

        CommentPanel.setBackground(new java.awt.Color(0, 0, 0));
        CommentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ConfirmBtn.setBackground(new java.awt.Color(255, 255, 255));
        ConfirmBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 5, 1));
        ConfirmBtn.setText("Confirm");
        ConfirmBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ConfirmBtn.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        ConfirmBtn.setkBorderRadius(45);
        ConfirmBtn.setkEndColor(new java.awt.Color(255, 255, 255));
        ConfirmBtn.setkForeGround(new java.awt.Color(0, 0, 0));
        ConfirmBtn.setkHoverColor(new java.awt.Color(204, 204, 204));
        ConfirmBtn.setkHoverEndColor(new java.awt.Color(204, 204, 204));
        ConfirmBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        ConfirmBtn.setkHoverStartColor(new java.awt.Color(204, 204, 204));
        ConfirmBtn.setkSelectedColor(new java.awt.Color(255, 255, 255));
        ConfirmBtn.setkStartColor(new java.awt.Color(255, 255, 255));
        ConfirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmBtnActionPerformed(evt);
            }
        });
        CommentPanel.add(ConfirmBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 110, 40));

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));

        CommentTable.setBackground(new java.awt.Color(0, 0, 0));
        CommentTable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CommentTable.setForeground(new java.awt.Color(255, 255, 255));
        CommentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Comments"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        CommentTable.setEnabled(false);
        CommentTable.setGridColor(new java.awt.Color(0, 0, 0));
        CommentTable.setSelectionBackground(new java.awt.Color(0, 0, 0));
        CommentTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(CommentTable);

        CommentPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 490, 350));

        InputComment.setBackground(new java.awt.Color(0, 0, 0));
        InputComment.setForeground(new java.awt.Color(255, 255, 255));
        InputComment.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        InputComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputCommentActionPerformed(evt);
            }
        });
        CommentPanel.add(InputComment, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 350, 40));

        GoBack.setForeground(new java.awt.Color(255, 255, 255));
        GoBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_back_25px.png"))); // NOI18N
        GoBack.setText("Back");
        GoBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GoBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GoBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GoBackMouseExited(evt);
            }
        });
        CommentPanel.add(GoBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 30));

        PageDetailLayout.add(CommentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 490, 490));

        PageDetailContent.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        PageDetailContent.setText("<html>Content Here</html> ");
        PageDetailLayout.add(PageDetailContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 810, 430));

        CommentBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 5, 1));
        CommentBtn.setText("Comment");
        CommentBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CommentBtn.setkBackGroundColor(new java.awt.Color(0, 0, 0));
        CommentBtn.setkBorderRadius(45);
        CommentBtn.setkEndColor(new java.awt.Color(0, 0, 0));
        CommentBtn.setkHoverColor(new java.awt.Color(204, 204, 204));
        CommentBtn.setkHoverEndColor(new java.awt.Color(204, 204, 204));
        CommentBtn.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        CommentBtn.setkHoverStartColor(new java.awt.Color(204, 204, 204));
        CommentBtn.setkIndicatorColor(new java.awt.Color(0, 0, 0));
        CommentBtn.setkSelectedColor(new java.awt.Color(0, 0, 0));
        CommentBtn.setkStartColor(new java.awt.Color(0, 0, 0));
        CommentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommentBtnActionPerformed(evt);
            }
        });
        PageDetailLayout.add(CommentBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 570, 160, 40));

        CardLayoutPanel.add(PageDetailLayout, "card2");

        FramePanel.add(CardLayoutPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, 650));

        getContentPane().add(FramePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 860));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        CardLayoutPanel.removeAll();
        CardLayoutPanel.add(SearchLayout);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_SearchBtnActionPerformed

    private void NewPostPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewPostPanelMouseEntered
        NewPostPanel.setBackground(new Color(230, 230, 230));
    }//GEN-LAST:event_NewPostPanelMouseEntered

    private void NewPostPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewPostPanelMouseExited
        NewPostPanel.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_NewPostPanelMouseExited

    private void NewPostPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewPostPanelMouseClicked
        CardLayoutPanel.removeAll();
        CardLayoutPanel.add(NewPostLayout);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_NewPostPanelMouseClicked

    private void NewPostLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewPostLabelMouseEntered
        NewPostPanel.setBackground(new Color(230, 230, 230));
    }//GEN-LAST:event_NewPostLabelMouseEntered

    private void NewPostLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewPostLabelMouseExited
        NewPostPanel.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_NewPostLabelMouseExited

    private void NewPostLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewPostLabelMouseClicked
        CardLayoutPanel.removeAll();
        CardLayoutPanel.add(NewPostLayout);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_NewPostLabelMouseClicked

    private void DashboardPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardPanelMouseEntered
        DashboardPanel.setBackground(new Color(230, 230, 230));
    }//GEN-LAST:event_DashboardPanelMouseEntered

    private void DashboardPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardPanelMouseExited
        DashboardPanel.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_DashboardPanelMouseExited

    private void DashboardPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardPanelMouseClicked
        CardLayoutPanel.removeAll();
        CardLayoutPanel.add(DashboardLayout);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_DashboardPanelMouseClicked

    private void DashboardLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardLabelMouseEntered
        DashboardPanel.setBackground(new Color(230, 230, 230));
    }//GEN-LAST:event_DashboardLabelMouseEntered

    private void DashboardLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardLabelMouseExited
        DashboardPanel.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_DashboardLabelMouseExited

    private void DashboardLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardLabelMouseClicked
        CardLayoutPanel.removeAll();
        CardLayoutPanel.add(DashboardLayout);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_DashboardLabelMouseClicked

    private void AboutUsPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutUsPanelMouseEntered
        AboutUsPanel.setBackground(new Color(230, 230, 230));
    }//GEN-LAST:event_AboutUsPanelMouseEntered

    private void AboutUsPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutUsPanelMouseExited
        AboutUsPanel.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_AboutUsPanelMouseExited

    private void AboutUsPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutUsPanelMouseClicked
        CardLayoutPanel.removeAll();
        CardLayoutPanel.add(AboutUsLayout);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_AboutUsPanelMouseClicked

    private void AboutUsLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutUsLabelMouseEntered
        AboutUsPanel.setBackground(new Color(230, 230, 230));
    }//GEN-LAST:event_AboutUsLabelMouseEntered

    private void AboutUsLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutUsLabelMouseExited
        AboutUsPanel.setBackground(new Color(255, 255, 255));    }//GEN-LAST:event_AboutUsLabelMouseExited

    private void AboutUsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutUsLabelMouseClicked
        CardLayoutPanel.removeAll();
        CardLayoutPanel.add(AboutUsLayout);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_AboutUsLabelMouseClicked

    private void LogoutPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutPanelMouseEntered
        LogoutPanel.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_LogoutPanelMouseEntered

    private void LogoutPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutPanelMouseExited
        LogoutPanel.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_LogoutPanelMouseExited

    private void LogoutPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutPanelMouseClicked
        close();
        LoginPage form = new LoginPage();
        form.setVisible(true);
    }//GEN-LAST:event_LogoutPanelMouseClicked

    private void LogoutLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutLabelMouseEntered
        LogoutPanel.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_LogoutLabelMouseEntered

    private void LogoutLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutLabelMouseExited
        LogoutPanel.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_LogoutLabelMouseExited

    private void LogoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutLabelMouseClicked
        close();
        LoginPage form = new LoginPage();
        form.setVisible(true);
    }//GEN-LAST:event_LogoutLabelMouseClicked

    private void ExitPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitPanelMouseEntered
        ExitPanel.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_ExitPanelMouseEntered

    private void ExitPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitPanelMouseExited
        ExitPanel.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_ExitPanelMouseExited

    private void ExitPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitPanelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitPanelMouseClicked

    private void ExitLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitLabelMouseEntered
        ExitPanel.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_ExitLabelMouseEntered

    private void ExitLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitLabelMouseExited
        ExitPanel.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_ExitLabelMouseExited

    private void ExitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitLabelMouseClicked
//Form Window Open
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            setImagePage("/SunriseLake.png", Thumbnail1);
            setImagePage("/WindowsB.png", Thumbnail2);
        } catch (Exception e) {
        }
        
        setWelcomeLabel("Tricky");
        CommentPanel.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void ProfileLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfileLabelMouseClicked
        UserProfilePage form = new UserProfilePage();
        form.setVisible(true);
    }//GEN-LAST:event_ProfileLabelMouseClicked

    private void ProfileLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfileLabelMouseEntered
        
    }//GEN-LAST:event_ProfileLabelMouseEntered

    private void ProfileLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfileLabelMouseExited
        
    }//GEN-LAST:event_ProfileLabelMouseExited

    private void LogoLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoLabelMouseClicked
        CardLayoutPanel.removeAll();
        CardLayoutPanel.add(HomeLayout);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_LogoLabelMouseClicked

    private void LabelPost1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelPost1MouseClicked
        CardLayoutPanel.removeAll();
        CardLayoutPanel.add(PageDetailLayout);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
        try {
            fillToDetailPage("/SunriseLake.png", PageDetailImage, "");
        } catch (IOException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_LabelPost1MouseClicked

    private void LabelPost2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelPost2MouseClicked
        CardLayoutPanel.removeAll();
        CardLayoutPanel.add(PageDetailLayout);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
        try {
            fillToDetailPage("/WindowB.png", Thumbnail2, "");
        } catch (IOException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_LabelPost2MouseClicked

    private void CommentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommentBtnActionPerformed
        CommentPanel.setVisible(true);

    }//GEN-LAST:event_CommentBtnActionPerformed

    private void InputCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputCommentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputCommentActionPerformed

    private void ConfirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmBtnActionPerformed
        
    }//GEN-LAST:event_ConfirmBtnActionPerformed

    private void GoBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoBackMouseEntered
        GoBack.setForeground(new Color(204, 204, 204));
    }//GEN-LAST:event_GoBackMouseEntered

    private void GoBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoBackMouseExited
        GoBack.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_GoBackMouseExited

    private void GoBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoBackMouseClicked
        CommentPanel.setVisible(false);
    }//GEN-LAST:event_GoBackMouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }
    
    int colorCount = 0;
    

// code upgrading    
//    public void getpicture() throws IOException {
//        try {
//            URL url = getClass().getResource("/WindowsB.png");
//            File file = new File(url.getPath());
//            //File file = new File("C:\\Users\\ASUS\\Downloads\\ma.png");
//            Image image = ImageIO.read(file);
//            Thumbnail2.setText("");
//            int height = Thumbnail2.getHeight();
//            int width = Thumbnail2.getWidth();
//            Thumbnail2.setIcon(new ImageIcon(image.getScaledInstance(width, height, 0)));
//
//           String imagePath = file.getAbsolutePath();
//        } catch (Exception e) {
//            e.getStackTrace();
//        }
//
//    }
    
    public void fillToDetailPage(String imagePath, JLabel imageJLabel, String pageContent) throws IOException{
        setImagePage(imagePath, imageJLabel);
        
        PageDetailContent.setText("");
        
    }
    
    public void setImagePage(String imagePath, JLabel imageLabel) throws IOException {
        try {
            
            URL url = getClass().getResource(imagePath); // them anh trang detail vao day
            File file = new File(url.getPath());

            Image image = ImageIO.read(file);
            imageLabel.setText("");
            int height = imageLabel.getHeight();
            int width = imageLabel.getWidth();
            imageLabel.setIcon(new ImageIcon(image.getScaledInstance(width, height, 0)));
        } catch (Exception e) {
            e.getStackTrace();
        }

    }

    public void close() {
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }

    public void setWelcomeLabel(String username){
        String stringWelcome = "Welcome " + username;
        WelcomeLabel.setText(stringWelcome);
    } 
    
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AboutUsLabel;
    private javax.swing.JPanel AboutUsLayout;
    private javax.swing.JPanel AboutUsPanel;
    private javax.swing.JPanel CardLayoutPanel;
    private com.k33ptoo.components.KButton CommentBtn;
    private javax.swing.JPanel CommentPanel;
    private javax.swing.JTable CommentTable;
    private com.k33ptoo.components.KButton ConfirmBtn;
    private javax.swing.JLabel DashboardLabel;
    private javax.swing.JPanel DashboardLayout;
    private javax.swing.JPanel DashboardPanel;
    private javax.swing.JLabel DetailPageTitle;
    private javax.swing.JLabel ExitLabel;
    private javax.swing.JPanel ExitPanel;
    private com.k33ptoo.components.KGradientPanel FramePanel;
    private javax.swing.JLabel GoBack;
    private javax.swing.JPanel HomeLayout;
    private javax.swing.JTextField InputComment;
    private javax.swing.JLabel LabelPost1;
    private javax.swing.JLabel LabelPost2;
    private javax.swing.JLabel LogoLabel;
    private javax.swing.JLabel LogoutLabel;
    private javax.swing.JPanel LogoutPanel;
    private javax.swing.JLabel MainLabelPost;
    private javax.swing.JPanel MainPostLabelPanel;
    private javax.swing.JLabel MainThumbnail;
    private javax.swing.JPanel MenuLine1;
    private javax.swing.JPanel MenuLine2;
    private javax.swing.JLabel NewPostLabel;
    private javax.swing.JPanel NewPostLayout;
    private javax.swing.JPanel NewPostPanel;
    private javax.swing.JLabel PageDetailContent;
    private javax.swing.JLabel PageDetailImage;
    private javax.swing.JPanel PageDetailLayout;
    private javax.swing.JLabel ProfileLabel;
    private javax.swing.JPanel SayWelcome;
    private com.k33ptoo.components.KButton SearchBtn;
    private javax.swing.JTextField SearchInput;
    private javax.swing.JPanel SearchLayout;
    private javax.swing.JLabel Thumbnail1;
    private javax.swing.JLabel Thumbnail2;
    private javax.swing.JLabel TopicMainPost;
    private javax.swing.JLabel WelcomeLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
